# Generated by Django 3.1.2 on 2020-10-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(default='2020-10-29 23:08:37.668976', max_length=100, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Заголовок (title)')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Основной текст поста')),
                ('photo', models.ImageField(blank=True, upload_to='blog/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=False, verbose_name='Выложить на сайт')),
            ],
        ),
    ]
